name: manga_reader
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  provider: ^4.3.3
  font_awesome_flutter: ^8.12.0
  shared_preferences: ^0.5.12+4
  floating_bottom_navigation_bar: ^1.4.1
  flutter_launcher_icons: ^0.7.2
  get_it: ^5.0.6
  simple_search_bar: ^0.1.7
  dio: ^3.0.10
  photo_view: ^0.10.3
  cached_network_image: ^2.5.1
  flutter_image: ^3.0.0
  flutter_downloader: ^1.5.2
  permission_handler: ^5.1.0+2
  path_provider: ^1.6.27
  sembast: ^2.4.10+4
  dartz: ^0.9.2
  flutter_rating_bar: ^3.2.0+1
  simple_moment: ^1.0.7
  quiver:
  flutter_archive: ^2.0.2
  bot_toast: ^3.0.5
  carousel_slider: ^3.0.0
  modal_bottom_sheet: ^1.0.0+1
  expandable: ^4.1.4
  url_launcher: ^5.7.10
  wakelock: ^0.2.1+1
  esys_flutter_share: ^1.0.2
  ext_storage: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/fanga.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
